version: '3'
services:
  mongodb:  #imagename
      image: mongo:latest
      container_name: mongodb
      restart: always
      ports: 
        - 27017:27017
      environment:
        - MONGO_INITDB_ROOT_USERNAME=marcosanoandrea 
        - MONGO_INITDB_ROOT_PASSWORD=9124
      networks:
        - my_network
      volumes:
        - db-data:/data/db
  mongo-express:  #imagename
      image: mongo-express
      container_name: mongo-express
      ports: 
        - 8081:8081
      environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=marcosanoandrea  
        - ME_CONFIG_MONGODB_ADMINPASSWORD=9124 
        - ME_CONFIG_MONGODB_SERVER=mongodb
      networks:
        - my_network
  #app:
    #build: ./src
    #ports:
     # - 3000:3000
    #depends_on: 
     # - mongodb
    #networks:
     # - my_network

networks:
  my_network:
    driver: bridge
volumes:
  db-data:
    driver: local 

